import { LayerTypes } from 'widgets/LayersSection/types';

enum Tool {
  Font = 'Font',
  FontSize = 'FontSize',
  Bold = 'Bold',
  Italic = 'Italic',
  Underline = 'Underline',
  Highlight = 'Highlight',
  Fill = 'Fill',
  Caps = 'Caps',
  TextAlignment = 'TextAlignment',
  Spacing = 'Spacing',
  Bend = 'Bend',
  TextStyles = 'TextStyles',
  Edit = 'Edit',
  Animations = 'Animations',
  AlignObject = 'AlignObject',
  FlipRotate = 'FlipRotate',
  Duplicate = 'Duplicate',
  Delete = 'Delete',
  Adjust = 'Adjust',
  Effects = 'Effects',
  RemoveBg = 'RemoveBg',
  Remove = 'Remove',
  AiEnhance = 'AiEnhance',
  Erase = 'Erase',
  Crop = 'Crop',
  Replace = 'Replace',
}

type Tools = Record<LayerTypes, Tool[]>;

export const tools: Tools = {
  [LayerTypes.Text]: [
    Tool.Edit,
    Tool.FlipRotate,
    Tool.Duplicate,
    Tool.Delete,
    Tool.AlignObject,
    Tool.Font,
    Tool.FontSize,
    Tool.Bold,
    Tool.Italic,
    Tool.Highlight,
    Tool.Fill,
    Tool.Caps,
    Tool.TextAlignment,
    Tool.Spacing,
    Tool.TextStyles,
    Tool.Animations,
  ],
  [LayerTypes.Image]: [
    Tool.Edit,
    Tool.FlipRotate,
    Tool.Duplicate,
    Tool.Delete,
    Tool.AlignObject,
    Tool.Adjust,
    Tool.Effects,
    Tool.RemoveBg,
    Tool.Remove,
    Tool.AiEnhance,
    Tool.Erase,
    Tool.Animations,
    Tool.Crop,
    Tool.Replace,
  ],
  [LayerTypes.Sticker]: [
    Tool.Edit,
    Tool.FlipRotate,
    Tool.Duplicate,
    Tool.Delete,
    Tool.AlignObject,
    Tool.Erase,
    Tool.Adjust,
    Tool.Fill,
    Tool.Remove,
    Tool.Animations,
  ],
  [LayerTypes.Shape]: [
    Tool.Edit,
    Tool.FlipRotate,
    Tool.Duplicate,
    Tool.Delete,
    Tool.AlignObject,
    Tool.Adjust,
    Tool.Fill,
    Tool.Animations,
  ],
  [LayerTypes.Background]: [
    Tool.Edit,
    Tool.FlipRotate,
    Tool.Duplicate,
    Tool.Delete,
    Tool.AlignObject,
    Tool.Adjust,
    Tool.Effects,
    Tool.RemoveBg,
    Tool.Remove,
    Tool.AiEnhance,
    Tool.Erase,
    Tool.Crop,
  ],
  [LayerTypes.Collage]: [
    Tool.Edit,
    Tool.FlipRotate,
    Tool.Duplicate,
    Tool.Delete,
    Tool.AlignObject,
    Tool.Adjust,
    Tool.Fill,
    Tool.Animations,
  ]
};